// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { eZKlaimNoVerify$Type } from "./eZKlaimNoVerify";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["eZKlaimNoVerify"]: eZKlaimNoVerify$Type;
    ["contracts/ezklaimNoVerify.sol:eZKlaimNoVerify"]: eZKlaimNoVerify$Type;
  }
}
