[package]
name = "ezklaim_circuit"
type = "bin"
authors = [""]
compiler_version = ">0.19.0"

[dependencies]
rsa = { tag = "main", git = "https://github.com/SetProtocol/noir-rsa", directory="crates/rsa" }
rsabigint = { tag = "main", git = "https://github.com/SetProtocol/noir-rsa", directory="crates/rsa-biguint"}
